//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleServiceContractClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INormalCal")]
    public interface INormalCal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INormalCal/AddInt", ReplyAction="http://tempuri.org/INormalCal/AddIntResponse")]
        int AddInt(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INormalCal/AddInt", ReplyAction="http://tempuri.org/INormalCal/AddIntResponse")]
        System.Threading.Tasks.Task<int> AddIntAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INormalCal/AddString", ReplyAction="http://tempuri.org/INormalCal/AddStringResponse")]
        string AddString(string a, string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INormalCal/AddString", ReplyAction="http://tempuri.org/INormalCal/AddStringResponse")]
        System.Threading.Tasks.Task<string> AddStringAsync(string a, string b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INormalCalChannel : global::MultipleServiceContractClient.ServiceReference1.INormalCal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NormalCalClient : System.ServiceModel.ClientBase<global::MultipleServiceContractClient.ServiceReference1.INormalCal>, global::MultipleServiceContractClient.ServiceReference1.INormalCal {
        
        public NormalCalClient() {
        }
        
        public NormalCalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NormalCalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NormalCalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NormalCalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddInt(int a, int b) {
            return base.Channel.AddInt(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddIntAsync(int a, int b) {
            return base.Channel.AddIntAsync(a, b);
        }
        
        public string AddString(string a, string b) {
            return base.Channel.AddString(a, b);
        }
        
        public System.Threading.Tasks.Task<string> AddStringAsync(string a, string b) {
            return base.Channel.AddStringAsync(a, b);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBankCal")]
    public interface IBankCal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankCal/GetBalanace", ReplyAction="http://tempuri.org/IBankCal/GetBalanaceResponse")]
        double GetBalanace(string accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankCal/GetBalanace", ReplyAction="http://tempuri.org/IBankCal/GetBalanaceResponse")]
        System.Threading.Tasks.Task<double> GetBalanaceAsync(string accountid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankCalChannel : global::MultipleServiceContractClient.ServiceReference1.IBankCal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankCalClient : System.ServiceModel.ClientBase<global::MultipleServiceContractClient.ServiceReference1.IBankCal>, global::MultipleServiceContractClient.ServiceReference1.IBankCal {
        
        public BankCalClient() {
        }
        
        public BankCalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankCalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankCalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankCalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetBalanace(string accountid) {
            return base.Channel.GetBalanace(accountid);
        }
        
        public System.Threading.Tasks.Task<double> GetBalanaceAsync(string accountid) {
            return base.Channel.GetBalanaceAsync(accountid);
        }
    }
}
