//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorService.ConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBloodDonorService")]
    public interface IBloodDonorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBloodDonorService/GetTopDonor", ReplyAction="http://tempuri.org/IBloodDonorService/GetTopDonorResponse")]
        string GetTopDonor(string GroupName, int PinCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBloodDonorService/GetTopDonor", ReplyAction="http://tempuri.org/IBloodDonorService/GetTopDonorResponse")]
        System.Threading.Tasks.Task<string> GetTopDonorAsync(string GroupName, int PinCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBloodDonorServiceChannel : global::BloodDonorService.ConsoleClient.ServiceReference1.IBloodDonorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BloodDonorServiceClient : System.ServiceModel.ClientBase<global::BloodDonorService.ConsoleClient.ServiceReference1.IBloodDonorService>, global::BloodDonorService.ConsoleClient.ServiceReference1.IBloodDonorService {
        
        public BloodDonorServiceClient() {
        }
        
        public BloodDonorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BloodDonorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BloodDonorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BloodDonorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTopDonor(string GroupName, int PinCode) {
            return base.Channel.GetTopDonor(GroupName, PinCode);
        }
        
        public System.Threading.Tasks.Task<string> GetTopDonorAsync(string GroupName, int PinCode) {
            return base.Channel.GetTopDonorAsync(GroupName, PinCode);
        }
    }
}
